### ISSUE TITLE
structure of dataset

### ISSUE THREAD

**Issue by vaklyuenkov** [alfonsolink/roidb_maker#1]
Hello! Code is asking for  "/VOC2012/inst/image_name.mat" and "/VOC2012/cls/image_name.mat". Where one can get it? Thank you.

**Comment by alfonsolink** [comment]
Hi there:

For the roidb to work for PASCAL VOC, these steps (so far) are needed:

1) get the PASCAL VOC 2012 SDS dataset http://home.bharathh.info/home/sbd, and I put the main folder in my home directory
2) I renamed the SDS folder to 'VOCbenchmark', and the folder inside as
'VOC2012'
3) after downloading the sample roidb code in my github repo, include its
roidb_maker/lib folder in your PYTHONPATH
4) change all occurences of '/home/pancho' in roidb_maker/lib/db/imdb.py
and roidb_maker/lib/datasets/pascal_voc_det.py to your local
'/home/<username>'
5) run pre_proc.py inside roidb_maker and you should get roidb.pkl and
maskdb.pkl if all is fine
6) the roidb.pkl is the input for my faster_rcnn_dynamic code

Pls let me know if this is ok

**Comment by vaklyuenkov** [comment]
Solution work! Thank you very much.

**Comment by alfonsolink** [comment]
Hi, good to know, I just updated roidb_maker to also process xml from
PASCAL VOC 2007, same steps to be followed
